server:
  port: 8090
spring:
  application:
    name: simple-alert-remote-spring-boot-web
  profiles:
    active: mysql
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 20MB
      max-request-size: 100MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
ribbon:
  eureka:
    enabled: true
simple:
  alert:
    remote:
      mode: discovery
    config:
      push:
        mode: DingTalk
        webhook:
          token: 2624fdbbe5dbe8c0515c6fb02ba965c7321e8e487992b7f80fb1dd9435aa1a07
#日志配置
logging:
  config: classpath:logging-config.xml
  level:
    org:
      springframework:
        web: info
  pattern:
    #     日志高亮
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
